### ISSUE TITLE
Change Icon

### ISSUE THREAD

**Issue by fredarend** [mrohnstock/leaflet-awesome-markers#1]
How do I use another icon? I would like to use this:

http://fontawesome.io/icon/building-o/

But this way it does not work

`icon: {
type: 'awesomeMarker',
icon: 'building-o',
markerColor: 'blue'
},`

Help?

**Comment by mrohnstock** [comment]
well you should ask your question to the devs of leaflet-awesome-markers, as this is only a shim repository.

https://github.com/lvoogdt/Leaflet.awesome-markers
